language: python

cache: pip
  
# Enable 3.7 without globally enabling sudo and xenial
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - TEST_DIR=/tmp/_altair/

before_install:
  - pip install pip --upgrade;
  - pip install -U pytest flake8;

install:
  - pip install -e .;

script:
  - flake8 ./;
  - mkdir -p $TEST_DIR
  - cd $TEST_DIR && python -m pytest altair_pandas --pyargs --doctest-modules --backend_name=altair;
